language: generic
sudo: required
services:
  - docker

before_install: 
  - docker build -t avoup/docker-test -f Dockerfile.dev .

script:
  - docker run -e CI=true avoup/docker-test npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-test"
  env: "Dockertest-env"
  bucket_name: "elasticbeanstalk-us-east-1-590049449125"
  bucket_path: "docker-test"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"